spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#  session:
#    store-type: jdbc
  mustache:
    expose-session-attributes: true